### ISSUE TITLE
'nohelp' flag doesn't seem to work

### ISSUE THREAD

**Issue by freeze-dolphin** [Redempt/RedLib#11]
### commands.rdcml
```
dolphin-util {
	nohelp
	
	fetch-url string:url string:targetPath {
		nohelp
		permission dolphin-utility.access.fetch-url
		hook dolphin-util.fetch-url
	}
	
	config-reload {
		nohelp
		permission dolphin-utility.access.reload-config
		hook dolphin-util.reload-config
	}
}
```

### server_log.log
```
> dolphin-util fetch-url awdafadljas;ldkjasdfl;sakdjf
[11:25:52 INFO]: Incorrect number of arguments. Expected 2 argument(s), got 1
[11:25:52 INFO]: --[ Help for fetch-url ]--
[11:25:52 INFO]:
```

## Problem(s) I met
+ I attached the `nohelp` tag and expected it not to show anything about help message, but it performed 'beyond' my expectation.

**Comment by boxbeam** [comment]
This isn't a problem with the "nohelp" tag, it's an issue with help showing when it shouldn't. Maybe it's unclear, but that's not actually what the nohelp tag does. The nohelp tag makes it so that when you run `/command help` it doesn't show the help menu. Commands have an automatic `help` subcommand by default, the nohelp tag removes it. I will fix the issue with showing empty help, though.

**Comment by boxbeam** [comment]
Fixed with https://github.com/Redempt/RedLib/commit/d2590d4d30458eb192fce3bfa2b4bc98effca6d5
