### ISSUE TITLE
[Feature Request] Make a shaded library

### ISSUE THREAD

**Issue by Kylepoops** [Redempt/RedLib#7]
Make a shaded library so we don't need to install redlib in server when coding using redlib
And it's better to make each feature a stand-alone dependence

**Comment by boxbeam** [comment]
RedLib is not a shaded library because there's a tradeoff to shading. I decided to make RedLib standalone because I think it makes more sense for this dependency. It has some of its own commands and features, as well as its own messages that are configurable globally. Shading means that if a bug is fixed, you will need to recompile every plugin that uses it. It also inflates the jar size of all your plugins. For these reasons, RedLib is and will remain an external dependency.
